---
- name: varck
  hosts: tier2
  vars:
  - msg: "{{ansible_env.install_scenario|default('Not found')}}"
  tasks:
  - name: Print install_scenario
    debug: var=msg

  - name: Actually epected here
    vars:
    local_home: "{{ lookup('env','install_scenario') }}"
    
  - debug: var=ansible_env

