---
- name: varck
  hosts: tier2
  vars:
  - msg: "{{ansible_env.install_scenario|default('Not found')}}"
  - inst: "{{ lookup('env','install_scenario') }}"

  tasks:
  - name: Print install_scenario
    debug: var=msg

  - name: Actually expected here
    debug: var=inst
