---
# This playbook uses the win_ping module to test connectivity to Windows hosts
- name: Ping 
  hosts: all 

  tasks:
  - name: ping
    win_ping:

  - name: Pausing  2700s  as if waiting for something....  NO SMARTS YET
    pause:
      seconds: 2700
      prompt: no

